Repository pheature-flags/toggle-model, pull requests merged in 2021-11, with the labels that each got.

#14 Unable to load SegmentFactory from container in a Mezzio project
  composer.json
Labels: bug

#19 [#18] Run CI both PHP 7.4 and 8.0
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: dependencies

#20 [#12] Add support for PHP 8.1
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  composer.json
  phpcs.xml.dist
Labels: enhancement, dependencies
